### ISSUE TITLE
Error creating fuzzer

### ISSUE THREAD

**Issue by x62275** [shellphish/fuzzer#21]
I followed "[Install the CRS](https://github.com/mechaphish/mecha-docs/blob/master/development.md#install-the-crs)" instructions.
Next I did: `workon cgc`, then attempted to run shellphuzz on a simple binary:
`../angr-dev/fuzzer/shellphuzz -i -c 4 mybinary`.  The following error immediately appeared.

[*] Creating fuzzer...
ERROR   | 2017-08-31 16:44:15,218 | fuzzer.fuzzer | AFL Error: Pipe at the beginning of core_pattern
execute 'echo core | sudo tee /proc/sys/kernel/core_pattern'
AFL Warning: We probably want the fork() children to run first
execute 'echo 1 | sudo tee /proc/sys/kernel/sched_child_runs_first'

Traceback (most recent call last):
  File "../angr-dev/fuzzer/shellphuzz", line 69, in <module>
    create_dictionary=not args.no_dictionary, stuck_callback=stuck_callback, time_limit=args.timeout
  File "../angr-dev/fuzzer/fuzzer/fuzzer.py", line 97, in __init__
    Fuzzer._perform_env_checks()
  File "../angr-dev/fuzzer/fuzzer/fuzzer.py", line 595, in _perform_env_checks
    raise InstallError(err)
fuzzer.fuzzer.InstallError: AFL Error: Pipe at the beginning of core_pattern
execute 'echo core | sudo tee /proc/sys/kernel/core_pattern'
AFL Warning: We probably want the fork() children to run first
execute 'echo 1 | sudo tee /proc/sys/kernel/sched_child_runs_first'

Exception AttributeError: "'Fuzzer' object has no attribute 'procs'" in <bound method Fuzzer.__del__ of <fuzzer.fuzzer.Fuzzer object at 0x7f183b326f50>> ignored

**Comment by zardus** [comment]
Please read the content of that exception:

```fuzzer.fuzzer.InstallError: AFL Error: Pipe at the beginning of core_pattern
execute 'echo core | sudo tee /proc/sys/kernel/core_pattern'
AFL Warning: We probably want the fork() children to run first
execute 'echo 1 | sudo tee /proc/sys/kernel/sched_child_runs_first'
```

Aside from this (which must be resolved on the host machine before you can fuzz), my suggestion is to save your sanity and use the docker container: `docker run -it shellphish/mechaphish`.

**Comment by x62275** [comment]
You just saved me a lot of time.
