### ISSUE TITLE
Installing shellphish-afl to use with fuzzer

### ISSUE THREAD

**Issue by baileynottingham** [shellphish/fuzzer#25]
I am doing 'pip install git+https://github.com/shellphish/shellphish-afl' to download shellphish-afl but am getting this error during installation.

<img width="752" alt="screen shot 2018-02-01 at 7 16 20 pm" src="https://user-images.githubusercontent.com/27757796/35713489-d18363ae-0784-11e8-8a4a-bbd4cc27afca.png">

Could anyone provide any details on how to resolve this issue?

**Comment by zardus** [comment]
We don't have the manpower to offer support for installing mechaphish components. I would recommend using the docker image (`docker run -it shellphish/mechaphish`) or seeing how it's built (https://github.com/mechaphish/setup/blob/master//Dockerfile).
