### ISSUE TITLE
AFL Error | Docker image -> shellphish/mechaphish

### ISSUE THREAD

**Issue by Bennoli13** [shellphish/fuzzer#26]
Hi guys,

I just pull shellphish/mechaphish docker image and tried to run test_fuzzer.py but it failed like picture below. I also make sure that all the requirements installed already but still don't know how to solve it. Any idea? 
![6](https://user-images.githubusercontent.com/34600849/35722008-99a460d6-082f-11e8-9d76-800b550cd43c.PNG)

**Comment by zardus** [comment]
First, the error message _literally_ gives you the exact command that you should run to resolve the issue. Second, this repo has multiple identical issues to this from people who also don’t read the error message and _also_ don’t search for the solution. Either of those resources can be used to fix this.

**Comment by Bennoli13** [comment]
I forgot to mention it, I already followed the error message but nothing happened. Because tee feedback said that the file is read only so I thought maybe there is something that I missed. 
So it is mean that the only solution of this problem I should run the command in the error message correctly right? Okay then. Thanks 😬

**Comment by zardus** [comment]
Try running that outside of the docker container.
