### ISSUE TITLE
shellphuzz - filepath for seed has to be open with 'rb' option

### ISSUE THREAD

**Issue by kburova** [shellphish/fuzzer#36]
Line 80:             
```
     with open(filepath) as seedfile:
            seeds.append(seedfile.read())
```
If 'rb' option isn't used,  "`a bytes-like object is required, not 'str'` " error occurs. Even if file has `b''` pre-pended. It adds `""` around bytes-like  string and sees it as normal string. Also, it reeds in a new line.

**Comment by rhelmot** [comment]
Thanks for reporting. Sorry for taking so long to get to it; things have been a little hectic.
