### ISSUE TITLE
Input binary

### ISSUE THREAD

**Issue by Elothis** [shellphish/fuzzer#37]
Hey,

Im currently looking into using Driller via this python wrapper, and cannot quite answer the following question from just the readme:

What kind of binary has to be specified via the command line for it to work? Is it just the normally compiled binary (standard gcc/g++) and AFL then works via qemu mode on it, or does it have to be instrumented and compiled with the AFL compiler (afl-cc)?

Thanks :)

**Comment by zardus** [comment]
It's the former, but keep in mind that angr's environment model is ...
lacking, so if your binary makes complex syscalls (with a very loose
definition of complex), there will be dragons.

**Comment by Elothis** [comment]
Thanks!
